// Ratings are flavor stats (1-99, Madden-style), not official figures.
// Photos/team/jersey/experience/college are pulled from ESPN's public roster data.
const QB_POOL = [
  { name: 'Patrick Mahomes',    team: 'KC',  jersey: '15', experience: 10, college: 'Texas Tech',        photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3139477.png', stats: { strength: 78, arm: 96, speed: 82, build: 80, accuracy: 93, awareness: 97 } },
  { name: 'Josh Allen',         team: 'BUF', jersey: '17', experience: 9,  college: 'Wyoming',           photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3918298.png', stats: { strength: 92, arm: 95, speed: 88, build: 90, accuracy: 85, awareness: 90 } },
  { name: 'Joe Burrow',         team: 'CIN', jersey: '9',  experience: 7,  college: 'LSU',                photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3915511.png', stats: { strength: 74, arm: 90, speed: 70, build: 75, accuracy: 95, awareness: 93 } },
  { name: 'Justin Herbert',     team: 'LAC', jersey: '10', experience: 7,  college: 'Oregon',             photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4038941.png', stats: { strength: 84, arm: 97, speed: 76, build: 88, accuracy: 89, awareness: 87 } },
  { name: 'Jalen Hurts',        team: 'PHI', jersey: '1',  experience: 7,  college: 'Oklahoma',           photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4040715.png', stats: { strength: 88, arm: 84, speed: 87, build: 89, accuracy: 86, awareness: 88 } },
  { name: 'Lamar Jackson',      team: 'BAL', jersey: '8',  experience: 9,  college: 'Louisville',         photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3916387.png', stats: { strength: 76, arm: 85, speed: 99, build: 78, accuracy: 87, awareness: 91 } },
  { name: 'Dak Prescott',       team: 'DAL', jersey: '4',  experience: 11, college: 'Mississippi State',  photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/2577417.png', stats: { strength: 82, arm: 87, speed: 75, build: 84, accuracy: 88, awareness: 86 } },
  { name: 'Trevor Lawrence',    team: 'JAX', jersey: '16', experience: 6,  college: 'Clemson',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4360310.png', stats: { strength: 79, arm: 92, speed: 73, build: 83, accuracy: 84, awareness: 80 } },
  { name: 'C.J. Stroud',        team: 'HOU', jersey: '7',  experience: 4,  college: 'Ohio State',         photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4432577.png', stats: { strength: 75, arm: 91, speed: 68, build: 80, accuracy: 90, awareness: 85 } },
  { name: 'Brock Purdy',        team: 'SF',  jersey: '13', experience: 5,  college: 'Iowa State',         photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4361741.png', stats: { strength: 65, arm: 78, speed: 66, build: 65, accuracy: 92, awareness: 89 } },
  { name: 'Jordan Love',        team: 'GB',  jersey: '10', experience: 7,  college: 'Utah State',         photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4036378.png', stats: { strength: 77, arm: 93, speed: 72, build: 81, accuracy: 83, awareness: 82 } },
  { name: 'Caleb Williams',     team: 'CHI', jersey: '18', experience: 3,  college: 'USC',                photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4431611.png', stats: { strength: 73, arm: 89, speed: 79, build: 76, accuracy: 85, awareness: 78 } },
  { name: 'Anthony Richardson', team: 'IND', jersey: '5',  experience: 4,  college: 'Florida',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4429084.png', stats: { strength: 90, arm: 94, speed: 93, build: 91, accuracy: 72, awareness: 70 } },
  { name: 'Kyler Murray',       team: 'MIN', jersey: '1',  experience: 8,  college: 'Oklahoma',           photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3917315.png', stats: { strength: 62, arm: 86, speed: 91, build: 60, accuracy: 84, awareness: 83 } },
  { name: 'Matthew Stafford',   team: 'LAR', jersey: '9',  experience: 18, college: 'Georgia',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/12483.png',   stats: { strength: 80, arm: 93, speed: 60, build: 82, accuracy: 87, awareness: 92 } },
  { name: 'Aaron Rodgers',      team: 'PIT', jersey: '8',  experience: 22, college: 'California',         photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/8439.png',    stats: { strength: 70, arm: 90, speed: 58, build: 76, accuracy: 91, awareness: 96 } },
  { name: 'Baker Mayfield',     team: 'TB',  jersey: '6',  experience: 9,  college: 'Oklahoma',           photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3052587.png', stats: { strength: 75, arm: 88, speed: 65, build: 74, accuracy: 86, awareness: 84 } },
  { name: 'Tua Tagovailoa',     team: 'ATL', jersey: '1',  experience: 7,  college: 'Alabama',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4241479.png', stats: { strength: 63, arm: 82, speed: 64, build: 62, accuracy: 90, awareness: 85 } },
  { name: 'Geno Smith',         team: 'NYJ', jersey: '7',  experience: 14, college: 'West Virginia',      photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/15864.png',  stats: { strength: 72, arm: 84, speed: 67, build: 75, accuracy: 85, awareness: 84 } },
  { name: 'Sam Darnold',        team: 'SEA', jersey: '14', experience: 9,  college: 'USC',                photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3912547.png', stats: { strength: 71, arm: 86, speed: 55, build: 74, accuracy: 86, awareness: 87 } },
  { name: 'Kirk Cousins',       team: 'LV',  jersey: '8',  experience: 15, college: 'Michigan State',     photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/14880.png',  stats: { strength: 69, arm: 85, speed: 52, build: 73, accuracy: 87, awareness: 88 } },
  { name: 'Deshaun Watson',     team: 'CLE', jersey: '4',  experience: 10, college: 'Clemson',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/3122840.png', stats: { strength: 78, arm: 88, speed: 80, build: 80, accuracy: 82, awareness: 79 } },
  { name: 'Jayden Daniels',     team: 'WAS', jersey: '5',  experience: 3,  college: 'LSU',                photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4426348.png', stats: { strength: 74, arm: 87, speed: 78, build: 76, accuracy: 84, awareness: 86 } },
  { name: 'Bryce Young',        team: 'CAR', jersey: '9',  experience: 4,  college: 'Alabama',            photo: 'https://a.espncdn.com/i/headshots/nfl/players/full/4685720.png', stats: { strength: 58, arm: 80, speed: 71, build: 55, accuracy: 84, awareness: 79 } }
];
